// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MakeBddName
{
    static class Vsix
    {
        public const string Id = "3ad8ab11-a54c-4f40-8926-d25d05ac7ec6";
        public const string Name = "Make BDD Name";
        public const string Description = @"A Visual Studio extension that adds menu commands to convert a class or method name to and from a BDD-style sentence.";
        public const string Language = "en-US";
        public const string Version = "1.4";
        public const string Author = "Justin Rockwood";
        public const string Tags = "bdd, unit test";
    }
}
