// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MakeBddName
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageGuidString = "c6f71eb1-1c7f-4158-877b-7d4b8e6dc5cc";
        public const string TopMenuGuidString = "98aed3f7-0463-4de4-91fd-1e66a0975e58";
        public const string MakeBddNameCmdSetGuidString = "939ce9d0-7724-4468-95c8-d073c7d5ea9e";
        public static Guid PackageGuid = new Guid(PackageGuidString);
        public static Guid TopMenuGuid = new Guid(TopMenuGuidString);
        public static Guid MakeBddNameCmdSetGuid = new Guid(MakeBddNameCmdSetGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TopMenu = 0x3001;
        public const int MakeBddNameCommandId = 0x0100;
    }
}
